### ISSUE TITLE
Fix runtime error when attempting to view statistics with only one game

### ISSUE THREAD

**Issue by ChicksWithBricksCome** [TheMuffinMane/Monty-Hall#1]
![image](https://github.com/user-attachments/assets/ae84306c-31f5-48ed-893f-2b025bf871ae)

Steps:

1. Start a game
2. Pick a door
3. Don't switch doors
4. Attempt to view statistics

Observe the runtime error that occurs.

**Comment by TheMuffinMane** [comment]
thank you!
